-- Seed data for products table - shoes only, matching user preferences from user_profiles

insert into public.products (
  product_id,
  name,
  brand,
  category,
  sub_category,
  price,
  currency,
  size,
  color,
  material,
  attributes,
  product_url,
  image_path,
  product_summary
) values

-- Nike shoes matching sleek profile preferences for usr_5n6k1e4f
(
  'prd_nike_court_001',
  'Court Vision Low',
  'Nike',
  'shoe',
  'sneaker',
  75.00,
  'USD',
  '10.5',
  'white',
  'leather',
  '{
    "brands": ["Nike"],
    "types": ["sneaker"],
    "colors": ["white"],
    "materials": ["leather"],
    "style_tags": ["sleek", "minimalist", "athletic", "modern"],
    "use_cases": ["casual", "everyday"],
    "profile": "low-profile"
  }'::jsonb,
  'https://www.nike.com/t/court-vision-low-mens-shoes-6pJSVp',
  'products/shoes/prd_nike_court_001.jpg',
  'Nike Court Vision Low with clean white leather upper and low-profile design. Sleek basketball-inspired silhouette for everyday wear.'
),
(
  'prd_nike_blazer_001',
  'Blazer Low 77',
  'Nike',
  'shoe',
  'sneaker',
  100.00,
  'USD',
  '10.5',
  'black',
  'leather',
  '{
    "brands": ["Nike"],
    "types": ["sneaker"],
    "colors": ["black"],
    "materials": ["leather"],
    "style_tags": ["sleek", "minimalist", "modern", "vintage"],
    "use_cases": ["casual", "everyday"],
    "profile": "low-profile"
  }'::jsonb,
  'https://www.nike.com/t/blazer-low-77-mens-shoes-M7RQDX',
  'products/shoes/prd_nike_blazer_001.jpg',
  'Nike Blazer Low 77 with premium black leather and vintage basketball aesthetic. Sleek low-profile design with modern appeal.'
),
(
  'prd_nike_react_001',
  'React Infinity Run Flyknit 3',
  'Nike',
  'shoe',
  'athletic',
  160.00,
  'USD',
  '10.5',
  'grey',
  'knit',
  '{
    "brands": ["Nike"],
    "types": ["athletic", "sneaker"],
    "colors": ["grey"],
    "materials": ["knit"],
    "style_tags": ["sleek", "performance", "modern", "athletic"],
    "use_cases": ["running", "gym", "casual"],
    "profile": "low-profile"
  }'::jsonb,
  'https://www.nike.com/t/react-infinity-run-flyknit-3-mens-road-running-shoes-N2FWxl',
  'products/shoes/prd_nike_react_001.jpg',
  'Nike React Infinity Run Flyknit 3 with responsive cushioning and breathable knit upper. Sleek performance running shoe for serious athletes.'
),
(
  'prd_nike_pegasus_001',
  'Air Zoom Pegasus 39',
  'Nike',
  'shoe',
  'athletic',
  130.00,
  'USD',
  '10.5',
  'navy',
  'mesh',
  '{
    "brands": ["Nike"],
    "types": ["athletic", "sneaker"],
    "colors": ["navy"],
    "materials": ["mesh"],
    "style_tags": ["sleek", "performance", "modern", "athletic"],
    "use_cases": ["running", "gym", "everyday"],
    "profile": "low-profile"
  }'::jsonb,
  'https://www.nike.com/t/air-zoom-pegasus-39-mens-road-running-shoes-dJp3Cf',
  'products/shoes/prd_nike_pegasus_001.jpg',
  'Nike Air Zoom Pegasus 39 with Zoom Air units and engineered mesh. Trusted running shoe with sleek profile and versatile performance.'
),
(
  'prd_nike_killshot_001',
  'Killshot 2',
  'Nike',
  'shoe',
  'sneaker',
  90.00,
  'USD',
  '10.5',
  'white',
  'leather',
  '{
    "brands": ["Nike"],
    "types": ["sneaker"],
    "colors": ["white"],
    "materials": ["leather"],
    "style_tags": ["sleek", "minimalist", "modern", "vintage"],
    "use_cases": ["casual", "everyday"],
    "profile": "low-profile"
  }'::jsonb,
  'https://www.nike.com/t/killshot-2-mens-shoes-NKG56F',
  'products/shoes/prd_nike_killshot_001.jpg',
  'Nike Killshot 2 with clean white leather upper and minimal branding. Sleek tennis-inspired design with low-profile silhouette.'
),
(
  'prd_nike_metcon_001',
  'Metcon 8',
  'Nike',
  'shoe',
  'athletic',
  150.00,
  'USD',
  '10.5',
  'black',
  'mesh',
  '{
    "brands": ["Nike"],
    "types": ["athletic", "sneaker"],
    "colors": ["black"],
    "materials": ["mesh"],
    "style_tags": ["sleek", "performance", "modern", "athletic"],
    "use_cases": ["gym", "training", "casual"],
    "profile": "low-profile"
  }'::jsonb,
  'https://www.nike.com/t/metcon-8-mens-workout-shoes-m2vNQV',
  'products/shoes/prd_nike_metcon_001.jpg',
  'Nike Metcon 8 with stable heel and flexible forefoot for cross-training. Sleek design built for high-intensity workouts and everyday wear.'
)
on conflict (product_id) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  sub_category = excluded.sub_category,
  price = excluded.price,
  currency = excluded.currency,
  size = excluded.size,
  color = excluded.color,
  material = excluded.material,
  attributes = excluded.attributes,
  product_url = excluded.product_url,
  image_path = excluded.image_path,
  product_summary = excluded.product_summary;